music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users, only: %i(new create show)
  resource :session, only: %i(new create destroy)
  resources :bands
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true
  
  def to_s
    self.class.name.to_s
  end
end

music_app/app/models/user.rb
class User < ApplicationRecord
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  
  before_validation :ensure_session_token
  
  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end
  
  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?
    user.has_password?(password) ? user : nil
  end
  
  attr_reader :password
  
  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end
  
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def has_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?
  
  def login!(user)
    session[:session_token] = user.reset_session_token!
  end
  
  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def logout!
    current_user.reset_session_token! if current_user
    session[:session_token] = nil
  end
  
  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end
  
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end
  
  def create
    band = Band.new(name: params[:band][:name])
    
    if band.save
      redirect_to bands_url
    else
      flash.now[:band] = "Your band sucks"
      render :new
    end
  end
  
  def new
    @band = Band.new
    render :new
  end
  
  def edit
    @band = Band.find(params[:id])
    render :edit
  end
  
  def show
    @band = Band.find(params[:id])
    render :show
  end
  
  def update
    band = Band.find(params[:id])
    
    if band.update_attributes(name: params[:band][:name])
      redirect_to band_url(band)
    else
      flash.now[:band] = "No chance, Lance"
      render :edit
    end
  end
  
  def destroy
    band = Band.find(params[:id])
    band.destroy
    redirect_to bands_url
  end
  
  private
  
  def band_params
    params.require(:band).permit(:name)
  end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end
  
  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    
    if user.nil?
      flash.now[:session] = "Invalid credentials"
      render :new
    else
      login!(user)
      flash[:session] = "Welcome back!"
      redirect_to user_url(user)
    end
  end
  
  def destroy
    logout!
    redirect_to new_session_url
  end
end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only: [:show]
  
  def new
    render :new
  end
  
  def create
    user = User.new(user_params)
    
    if user.save
      flash[:user] = "Account created!"
      login!(user)
      redirect_to user_url(user)
    else
      flash.now[:user] = "Invalid username or password"
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    render :show
  end
  
  private
  
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/views/bands/edit.html.erb
<h2>Edit <%= @band.name %>'s page</h2>

<%= render 'shared/resource_form', resource: @band, action: :edit %>

music_app/app/views/bands/index.html.erb
<h2>All the bands:</h2>

<ul>
  <% @bands.each do |band| %>
    <li><a href="<%= band_url(band) %>"> <%= band.name %> </a></li>
  <% end %>
</ul>

music_app/app/views/bands/new.html.erb
<h2>Enter a band</h2>

<%= render 'shared/resource_form', resource: @band, action: :new %>

music_app/app/views/bands/show.html.erb
<h2> <%= @band.name %> </h2>

<p>This band has no info :(</p>

<%= link_to "Update info", edit_band_url %>
<%= button_to "Delete this shitty band", band_url, method: "delete" %>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <header class="container">
      <%= image_tag("my_logo.png", size: "60x60") %>
      <h1>Music App</h1>
      
      <nav>
      <% if logged_in? %>
        <%= button_to "Logout", session_url, method: "delete"  %>
      <% else %>
        <%= link_to "Login", new_session_url %>
        <%= link_to "Sign up", new_user_url %>
      <% end %>
      </nav>
      
    </header>
    
    <%= yield %>
  </body>
</html>

music_app/app/views/shared/_resource_form.html.erb
<% case resource %>
<% when Band %>
  <% case action %>
  <% when :new %> 
    <% action_url = bands_url %>
    <% button_text = "Create!" %>
    <% verb = "post" %>
  <% when :edit %>  
    <% action_url = band_url %>
    <% button_text = "Update" %>
    <% verb = "patch" %>
  <% end %>
<% end %>

<form action="<%= action_url %>" method="post">
  <input type="hidden" name="_method" value="<%= verb %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label>
    <%= resource %> name:
    <input type="text" name="band[name]" value="<%= resource ? resource.name : "" %>">
  </label>
  
  <br>
  <input type="submit" value="<%= button_text %>"
  
  <p><%= flash.now[resource.to_s.downcase.to_sym] %></p>
</form>

music_app/app/views/shared/_user_form.html.erb
<% if type == :signup %>
  <% action_url = users_url %>
  <% button_text = "Create Account" %>
  <% render_param = :user %>
<% elsif type == :login %>
  <% action_url = session_url %>
  <% button_text = "Login" %>
  <% render_param = :session %>
<% end %>

<form action="<%= action_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  
  <label>
    Email:
    <input type="text" name="user[email]" value="">
  </label>
  <br><br>
  
  <label>
    Password:
    <input type="text" name="user[password]" value="">
  </label>
  <br><br>
  
  <input type="submit" value="<%= button_text %>">
  
  <p><%= flash.now[render_param] %></p>
  
</form>

music_app/app/views/users/new.html.erb
<h2>New User Form</h2>

<%= render 'shared/user_form', user: @user, type: :signup %>

music_app/app/views/users/show.html.erb
<p>This is <%= @user.email %>'s page.</p>
<br>
<p>You are browing as <%= current_user.email %> </p>

<p><%= flash[:user] %></p>
<p><%= flash[:session] %></p>